#ifndef STUDENT_H
#define STUDENT_H
#include <string>
#include <iostream>

class Student{
	private:
		int id;
		std::string name;
		std::string dorm;

	public:
		Student(int, std::string);
		int getID() const;
		std::string getName() const;
		std::string getDorm() const;

		// Friend function generated by LeChat, 09/27/2025
		friend std::ostream& operator<<(std::ostream& os, const Student& student){
			os << "Student(ID: " << student.id << ", Name: " << student.name << ")";
    		return os;
		}
};

#endif