# Creates a graph from text files in the working directory
import os
import matplotlib.pyplot as plt 
import numpy as np

# Function created by Copilot 09/11/2025
def plot_algorith_analysis():
    files = [f for f in os.listdir('.') if os.path.isfile(f) and f.endswith('.txt')]
    for file in files:
        print(f"Processing file: {file}")
        print(f"File contents")
        label = file.replace('.txt', '')
        data = np.loadtxt(file, delimiter=' ')
        x = data[:, 0]
        y = data[:, 1]
        plt.plot(x, y, label=label)
    
    # make the legend clickable to hide/show lines (generated by Copilot 09/14/2025)
    leg = plt.legend(loc='upper left')
    for legline in leg.get_lines():
        legline.set_picker(5)  # 5 pts tolerance

    def onpick(event):
        legline = event.artist
        origline = plt.gca().get_lines()[leg.get_lines().index(legline)]
        vis = not origline.get_visible()
        origline.set_visible(vis)
        if vis:
            legline.set_alpha(1.0)
        else:
            legline.set_alpha(0.2)
        plt.draw()

    plt.gcf().canvas.mpl_connect('pick_event', onpick)
    plt.xlabel('Problem size')
    plt.ylabel('Comparisons')
    plt.title('Algorithm Analysis')
    plt.show()

print("Generating graphs from text files...")
plot_algorith_analysis()