# Creates a graph from text files in the working directory
import os
import matplotlib.pyplot as plt 
import numpy as np

# Function created by Copilot 09/11/2025
def plot_algorith_analysis():
    # Look for files specifically in the Experiment2 directory
    target_dir = 'experiment2_3'
    
    # Check if the directory exists
    if not os.path.exists(target_dir):
        print(f"Error: Directory '{target_dir}' not found!")
        return
    # Get files from the Experiment2 directory only
    files = [f for f in os.listdir(target_dir) if os.path.isfile(os.path.join(target_dir, f)) and f.endswith('.txt')]
    if not files:
        print(f"No .txt files found in {target_dir} directory!")
        return
    
    for file in files:
        print(f"Processing file: {file}")
        print(f"File contents")
        label = file.replace('.txt', '')
        data = np.loadtxt(os.path.join(target_dir, file), delimiter=' ')
        x = data[:, 0]
        y = data[:, 1]
        plt.plot(x, y, label=label)
    
    # make the legend clickable to hide/show lines (generated by Copilot 09/14/2025)
    leg = plt.legend(loc='upper left')
    for legline in leg.get_lines():
        legline.set_picker(5)  # 5 pts tolerance

    def onpick(event):
        legline = event.artist
        origline = plt.gca().get_lines()[leg.get_lines().index(legline)]
        vis = not origline.get_visible()
        origline.set_visible(vis)
        if vis:
            legline.set_alpha(1.0)
        else:
            legline.set_alpha(0.2)
        plt.draw()

    plt.gcf().canvas.mpl_connect('pick_event', onpick)
    plt.xlabel('Problem size')
    plt.ylabel('Comparisons')
    plt.title('Worst Cast Comparison')
    plt.savefig('experiment2_3/worst_case_compss_analysis.png')

print("Generating graphs from text files...")
plot_algorith_analysis()